name: Run CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: black & isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: "23.1.0"
      - uses: isort/isort-action@v1.1.0
        with:
          isort-version: "5.12.0"
          configuration: "--check-only --diff --profile black"